title: Adam Ayala # your name (or website title) here
logo: "images/81716043.jfif" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate of Coding Dojo's part-time accelerated course. Experienced with many projects and assignments that helped grow my knowledge in full-stack developing.  
  <br><br>
  Excited to gain experience working in my new job field and to advance my skills even further. 
  <br><br>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
